version: '3'
services:
  bootstrap:
    container_name: bootstrap-node
    image: 'golang:latest'
    command: tail -F anything
    volumes:
      - .:/app
    networks:
      - app-network


  normal:
    container_name: normal-node
    image: 'golang:latest'
    command: tail -F anything
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge